package com.lushihao.picture.infrastructure.api.aliyunai.model;

import cn.hutool.core.annotation.Alias;
import lombok.Data;

import java.io.Serializable;

/**
 * 创建通用的图片风格处理请求、包含以下功能：
 * 图像风格化：全局风格化、局部风格化。
 * 图像内容编辑：指令编辑（无需指定区域，仅通过指令增加/修改图片内容）、局部重绘（针对指定区域增加/删除/修改图片内容）、去文字水印（中英文）。
 * 图像尺寸与分辨率优化：扩图（按比例扩图）、图像超分（高清放大）。
 * 图像色彩处理：图像上色（黑白或灰度图像转为彩色图像）。
 * 基于参考图像生成：线稿生图（先提取输入图像的线稿，再参考线稿生成图像）、参考卡通形象生图。
 * 这里仅实现全局风格化
 *
 * @author: lushihao
 * @version: 1.0
 * create:   2025-08-05   16:02
 */
@Data
public class CreateCommonSynthesisTaskRequest implements Serializable {

    private static final long serialVersionUID = -519740626712610275L;

    /**
     * 模型，例如 "wanx2.1-imageedit"
     */
    private String model = "wanx2.1-imageedit";

    /**
     * 输入图像信息
     */
    private CreateCommonSynthesisTaskRequest.Input input;

    /**
     * 图像处理参数
     */
    private CreateCommonSynthesisTaskRequest.Parameters parameters;

    @Data
    public static class Input {
        /**
         * 必选，图像 URL
         */
        @Alias("base_image_url")
        private String baseImageUrl;
        /**
         * 必选，处理功能，例如 "stylization_all"代表全局风格化
         * todo： 后续可以添加其他功能实现包含局部风格化 去水印等功能
         */
        private String function = "stylization_all";

        /**
         * 提示词 转换成xx风格
         */
        private String prompt;
    }

    @Data
    public static class Parameters implements Serializable {
        /**
         * 可选，生成图片的数量。取值范围为1~4张，默认为1。
         */
        private Integer n;

        /**
         * 随机数种子，用于控制模型生成内容的随机性。seed参数取值范围是[0, 2147483647]。
         * 如果不提供，则算法自动生成一个随机数作为种子。如果您希望生成内容保持相对稳定，请使用相同的seed参数值。
         */
        private Integer seed;

        /**
         * 可选，添加 "Generated by AI" 水印，默认值 true
         */
        @Alias("add_watermark")
        private Boolean addWatermark = false;
        /**
         * （可选）当function设置为 stylization_all（全局风格化）时填写。
         * 图像修改幅度。取值范围[0.0 1.0]，默认值为0.5。
         * 值越接近0，则越接近原图效果；值越接近1，对原图的修改幅度越大。
         */
        private Float strength;
    }

}
