spring:
  application:
    name: picture-backend-ddd
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 20MB     # 单个文件最大大小
      max-request-size: 20MB  # 总请求大小
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.lushihao.picturebackend.mybatis.entity

  global-config:
    db-config:
      table-underline: true # ✅ 表字段为下划线格式时加这个更保险
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
    enable-sql-runner: true




